# Install hyprland and its dependencies
hyprland
waybar (use jack2 for audio engineering driver, pipewire-jack for more modern but more basic driver)

# Copy the default config and style files
mkdir -p ~/.config/waybar
cp /etc/xdg/waybar/config ~/.config/waybar/
cp /etc/xdg/waybar/style.css ~/.config/waybar/

# Install basic font
ttf-jetbrains-mono — great for terminals

# Install basic tools
rofi
kitty
vim
dolphin or nautilus

# Run hyprland to autogenerate config file
``hyprland``

# Use vim to edit "~/.config/hypr/hyprland.conf"
- comment out autogenerated message
- set $menu to "rofi -show drun"
- set "exec-once = waybar"

# Install other fonts
noto-fonts — covers most Unicode
ttf-font-awesome — for icons in Rofi or status bars

# Install other tools
firefox
