[*]
# Global defaults
# fit auto calc
fit = on
fit-target = 1024
# threads and batch
parallel = 1
# cache
flash-attn = on

[qwen3.8-27b]
# model file
model = /home/kevano/.lmstudio/models/unsloth/Qwen3.8-27B-GGUF/Qwen3.8-27B-UD-Q4_K_M.gguf
# vision
mmproj = /home/kevano/.lmstudio/models/unsloth/Qwen3.8-27B-GGUF/mmproj-F16.gguf
no-mmproj-offload = true
# spec draft
spec-type = draft-mtp
spec-draft-ngl = all
spec-draft-n-max = 3
spec-draft-n-min = 0
spec-draft-p-min = 0.5
# fit auto calc
fit-ctx = 65536
# cache
kv-unified = true
cache-type-k = q8_0
cache-type-v = q8_0
# threads and batch
threads = 10
batch-size = 4096
ubatch-size = 2048
# model parameters
temp = 0.7
top-k = 20
top-p = 0.95
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.05

[qwen3.6-35b-a3b]
# model file
model = /home/kevano/.lmstudio/models/lmstudio-community/Qwen3.6-35B-A3B-GGUF/Qwen3.6-35B-A3B-Q4_K_M.gguf
# vision
mmproj = /home/kevano/.lmstudio/models/lmstudio-community/Qwen3.6-35B-A3B-GGUF/mmproj-Qwen3.6-35B-A3B-BF16.gguf
no-mmproj-offload = true
# fit auto calc
ctx-size = 131072
# threads and batch
threads = 7
batch-size = 1024
# model parameters
temp = 0.6
top-k = 20
top-p = 0.95
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.05

[gemma-4-31b-qat]
# model file
model = /home/kevano/.lmstudio/models/unsloth/gemma-4-31B-it-qat-GGUF/gemma-4-31B-it-qat-UD-Q4_K_XL.gguf
# vision
mmproj = /home/kevano/.lmstudio/models/unsloth/gemma-4-31B-it-qat-GGUF/mmproj-F32.gguf
no-mmproj-offload = true
# spec draft
spec-draft-model = /home/kevano/.lmstudio/models/unsloth/gemma-4-31B-it-qat-GGUF/gemma-4-31B-it-Q4_0-MTP.gguf
spec-type = draft-mtp
spec-draft-ngl = all
spec-draft-n-max = 3
spec-draft-n-min = 0
spec-draft-p-min = 0.5
# fit auto calc
ctx-size = 65536
# cache
no-kv-offload = true
# threads and batch
threads = 7
batch-size = 512

[gemma-4-26b-a4b-qat]
# model file
model = /home/kevano/.lmstudio/models/unsloth/gemma-4-26B-A4B-it-qat-GGUF/gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf
# vision
mmproj = /home/kevano/.lmstudio/models/unsloth/gemma-4-26B-A4B-it-qat-GGUF/mmproj-F32.gguf
no-mmproj-offload = true
# spec draft
spec-draft-model = /home/kevano/.lmstudio/models/unsloth/gemma-4-26B-A4B-it-qat-GGUF/gemma-4-26B-A4B-it-Q4_0-MTP.gguf
spec-type = draft-mtp
spec-draft-ngl = all
spec-draft-n-max = 3
spec-draft-n-min = 0
spec-draft-p-min = 0.5
# fit auto calc
ctx-size = 65536
# threads and batch
threads = 7
batch-size = 1024

[gemma-4-12b-qat]
# model file
model = /home/kevano/.lmstudio/models/unsloth/gemma-4-12B-it-qat-GGUF/gemma-4-12B-it-qat-UD-Q4_K_XL.gguf
# vision
mmproj = /home/kevano/.lmstudio/models/unsloth/gemma-4-12B-it-qat-GGUF/mmproj-F32.gguf
mmproj-offload = true
# spec draft
spec-draft-model = /home/kevano/.lmstudio/models/unsloth/gemma-4-12B-it-qat-GGUF/mtp-gemma-4-12B-it-Q4_0.gguf
spec-type = draft-mtp
spec-draft-ngl = all
spec-draft-n-max = 3
spec-draft-n-min = 0
spec-draft-p-min = 0.5
# fit auto calc
ctx-size = 131072
# threads and batch
threads = 7
batch-size = 1024

[gpt-oss-120b]
# model file
model = /home/kevano/.lmstudio/models/lmstudio-community/gpt-oss-120b-GGUF/gpt-oss-120b-MXFP4-00001-of-00002.gguf
# fit auto calc
ctx-size = 65536
# threads and batch
threads = 7
batch-size = 1024

[gpt-oss-20b]
# model file
model = /home/kevano/.lmstudio/models/lmstudio-community/gpt-oss-20b-GGUF/gpt-oss-20b-MXFP4.gguf
# fit auto calc
ctx-size = 65536
# threads and batch
threads = 7
batch-size = 1024
