[*]
# Global defaults

[qwen3.8-27b]
model = /home/kevano/.lmstudio/models/lmstudio-community/Qwen3.8-27B-GGUF/Qwen3.8-27B-Q4_K_M.gguf
mmproj = /home/kevano/.lmstudio/models/lmstudio-community/Qwen3.8-27B-GGUF/mmproj-Qwen3.8-27B-BF16.gguf
no-mmproj-offload = true
spec-type = draft-mtp
spec-draft-ngl = all
spec-draft-n-max = 3
spec-draft-n-min = 0
spec-draft-p-min = 0.60
threads = 7
ctx-size = 65536
no-kv-offload = true
kv-unified = true
parallel = 1
flash-attn = on
fit = on
fit-target = 1024
fit-ctx = 65536
batch-size = 4096
ubatch-size = 2048
temp = 1.0
top-k = 20
top-p = 0.95
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0

[qwen3.6-35b-a3b]
model = /home/kevano/.lmstudio/models/lmstudio-community/Qwen3.6-35B-A3B-GGUF/Qwen3.6-35B-A3B-Q4_K_M.gguf
mmproj = /home/kevano/.lmstudio/models/lmstudio-community/Qwen3.6-35B-A3B-GGUF/mmproj-Qwen3.6-35B-A3B-BF16.gguf
no-mmproj-offload = true
threads = 7
ctx-size = 131072
parallel = 1
flash-attn = on
fit = on
fit-target = 1024
batch-size = 512

[qwen3.6-35b-a3b-unsloth]
model = /home/kevano/.lmstudio/models/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
n-gpu-layers = 22
spec-type = draft-mtp
spec-draft-ngl = all
spec-draft-n-max = 3
spec-draft-n-min = 0
spec-draft-p-min = 0.60
threads = 7
ctx-size = 131072
parallel = 1
flash-attn = on
fit = on
fit-target = 1024
batch-size = 512

[gemma-4-31b-qat]
model = /home/kevano/.lmstudio/models/lmstudio-community/gemma-4-31B-it-QAT-GGUF/gemma-4-31B-it-QAT-Q4_0.gguf
mmproj = /home/kevano/.lmstudio/models/lmstudio-community/gemma-4-31B-it-QAT-GGUF/mmproj-gemma-4-31B-it-QAT-BF16.gguf
no-mmproj-offload = true
spec-draft-model = /home/kevano/.lmstudio/models/Simplepotat/gemma-4-31b-it-qat-q4_0-assistant-gguf/gemma-4-31b-it-qat-q4_0-assistant.gguf
spec-type = draft-mtp
spec-draft-ngl = all
spec-draft-n-max = 3
spec-draft-n-min = 0
spec-draft-p-min = 0.60
threads = 7
ctx-size = 65536
no-kv-offload = true
parallel = 1
flash-attn = on
fit = on
fit-target = 1024
batch-size = 512

[gemma-4-31b-qat-unsloth]
model = /home/kevano/.lmstudio/models/unsloth/gemma-4-31B-it-qat-GGUF/gemma-4-31B-it-qat-UD-Q4_K_XL.gguf
mmproj = /home/kevano/.lmstudio/models/unsloth/gemma-4-31B-it-qat-GGUF/mmproj-F32.gguf
no-mmproj-offload = true
spec-draft-model = /home/kevano/.lmstudio/models/unsloth/gemma-4-31B-it-qat-GGUF/gemma-4-31B-it-Q4_0-MTP.gguf
spec-type = draft-mtp
spec-draft-ngl = all
spec-draft-n-max = 3
spec-draft-n-min = 0
spec-draft-p-min = 0.60
threads = 7
ctx-size = 65536
no-kv-offload = true
parallel = 1
flash-attn = on
fit = on
fit-target = 1024
batch-size = 512

[gemma-4-26b-a4b-qat]
model = /home/kevano/.lmstudio/models/lmstudio-community/gemma-4-26B-A4B-it-QAT-GGUF/gemma-4-26B-A4B-it-QAT-Q4_0.gguf
mmproj = /home/kevano/.lmstudio/models/lmstudio-community/gemma-4-26B-A4B-it-QAT-GGUF/mmproj-gemma-4-26B-A4B-it-QAT-BF16.gguf
no-mmproj-offload = true
spec-draft-model = /home/kevano/.lmstudio/models/RachidAR/gemma-4-26B-A4B-it-qat-assistant-q4_0-gguf/gemma-4-26b-A4B-it-assistant-Q4_0.gguf
spec-type = draft-mtp
spec-draft-ngl = all
spec-draft-n-max = 3
spec-draft-n-min = 0
spec-draft-p-min = 0.60
threads = 7
ctx-size = 65536
parallel = 1
flash-attn = on
fit = on
fit-target = 1024
batch-size = 1024

[gemma-4-26b-a4b-qat-unsloth]
model = /home/kevano/.lmstudio/models/unsloth/gemma-4-26B-A4B-it-qat-GGUF/gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf
mmproj = /home/kevano/.lmstudio/models/unsloth/gemma-4-26B-A4B-it-qat-GGUF/mmproj-F32.gguf
no-mmproj-offload = true
spec-draft-model = /home/kevano/.lmstudio/models/unsloth/gemma-4-26B-A4B-it-qat-GGUF/gemma-4-26B-A4B-it-Q4_0-MTP.gguf
spec-type = draft-mtp
spec-draft-ngl = all
spec-draft-n-max = 3
spec-draft-n-min = 0
spec-draft-p-min = 0.60
threads = 7
ctx-size = 65536
parallel = 1
flash-attn = on
fit = on
fit-target = 1024
batch-size = 1024

[gemma-4-12b-qat]
model = /home/kevano/.lmstudio/models/lmstudio-community/gemma-4-12B-it-QAT-GGUF/gemma-4-12B-it-QAT-Q4_0.gguf
mmproj = /home/kevano/.lmstudio/models/lmstudio-community/gemma-4-12B-it-QAT-GGUF/mmproj-gemma-4-12B-it-QAT-BF16.gguf
mmproj-offload = true
spec-draft-model = /home/kevano/.lmstudio/models/unsloth/gemma-4-12B-it-qat-GGUF/gemma-4-12B-it-Q4_0-MTP.gguf
spec-type = draft-mtp
spec-draft-ngl = all
spec-draft-n-max = 3
spec-draft-n-min = 0
spec-draft-p-min = 0.60
threads = 7
ctx-size = 131072
parallel = 1
flash-attn = on
fit = on
fit-target = 1024
batch-size = 1024

[gemma-4-12b-unsloth]
model = /home/kevano/.lmstudio/models/unsloth/gemma-4-12b-it-GGUF/gemma-4-12b-it-UD-Q6_K_XL.gguf
mmproj = /home/kevano/.lmstudio/models/unsloth/gemma-4-12b-it-GGUF/mmproj-F32.gguf
mmproj-offload = true
spec-draft-model = /home/kevano/.lmstudio/models/unsloth/gemma-4-12b-it-GGUF/gemma-4-12b-it-Q8_0-MTP.gguf
spec-type = draft-mtp
spec-draft-ngl = all
spec-draft-n-max = 3
spec-draft-n-min = 0
spec-draft-p-min = 0.60
threads = 7
ctx-size = 131072
parallel = 1
flash-attn = on
fit = on
fit-target = 1024
batch-size = 1024

[gpt-oss-120b]
model = /home/kevano/.lmstudio/models/lmstudio-community/gpt-oss-120b-GGUF/gpt-oss-120b-MXFP4-00001-of-00002.gguf
threads = 7
ctx-size = 65536
flash-attn = on
fit = on
fit-target = 1024
batch-size = 1024

[gpt-oss-20b]
model = /home/kevano/.lmstudio/models/lmstudio-community/gpt-oss-20b-GGUF/gpt-oss-20b-MXFP4.gguf
threads = 7
ctx-size = 65536
flash-attn = on
fit = on
fit-target = 1024
batch-size = 1024

