#!/bin/bash

# Update package list
sudo apt update

# Install necessary tools
sudo apt install -y curl git

# Copy .rc files
cp ~/dotfiles-linux/.bashrc ~/.bashrc
cp ~/dotfiles-linux/.vimrc ~/.vimrc
cp ~/dotfiles-linux/.sqliterc ~/.sqliterc

# Copy the entire .config directory
cp -r ~/dotfiles-linux/.config ~/.config

# Source the new .bashrc
source ~/.bashrc

echo "Common setup complete!"
